Repository ZeeshanMukhtar1/OpenVerse, pull requests merged in 2024-10, with the labels that each got.

#61 Github CodeSource Full Stack MERN App
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/.gitignore
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/backend/controllers/explore.controller.js
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/backend/controllers/user.controller.js
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/backend/routes/explore.route.js
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/backend/routes/user.route.js
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/backend/server.js
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/.eslintrc.cjs
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/README.md
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/index.html
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/package-lock.json
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/package.json
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/postcss.config.js
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/public/bg.png
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/public/c++.svg
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/public/csharp.svg
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/public/css.svg
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/public/flutter.svg
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/public/github.svg
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/public/go.svg
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/public/html.svg
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/public/java.svg
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/public/javascript.svg
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/public/logo.png
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/public/python.svg
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/public/swift.svg
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/public/typescript.svg
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/public/vite.svg
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/src/App.jsx
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/src/components/Logout.jsx
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/src/components/ProfileInfo.jsx
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/src/components/Repo.jsx
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/src/components/Repos.jsx
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/src/components/Search.jsx
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/src/components/Sidebar.jsx
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/src/components/SortRepos.jsx
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/src/components/Spinner.jsx
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/src/index.css
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/src/main.jsx
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/src/pages/ExplorePage.jsx
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/src/pages/HomePage.jsx
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/src/pages/LikesPage.jsx
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/src/pages/LoginPage.jsx
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/src/pages/SignUpPage.jsx
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/src/utils/constants.js
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/src/utils/functions.js
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/tailwind.config.js
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/frontend/vite.config.js
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/package-lock.json
  JavaScript/MERN Projects/Github CodeSource Full Stack Mern App/package.json
Labels: hacktoberfest-accepted

#63 Added Functional TodoApp (Frontned)
  JavaScript/Frontend-TodoApp/README.md
  JavaScript/Frontend-TodoApp/index.html
  JavaScript/Frontend-TodoApp/todo.css
  JavaScript/Frontend-TodoApp/todo.js
Labels: hacktoberfest-accepted

#66 CPP: add binary exponent
  Cpp/math/binary-exponent.cpp
Labels: Hacktoberfest

#68 a simple todo application added
  JavaScript/simpleTodo/index.html
Labels: Hacktoberfest

#70 added mazesolver.py
  Python/Python algorithm/mazesolver.py
Labels: Hacktoberfest

#72 Theme Generator
  JavaScript/Color Palette Generator/index.css
  JavaScript/Color Palette Generator/index.html
  JavaScript/Color Palette Generator/index.js
Labels: Hacktoberfest

#73 simple weather app added
  JavaScript/weatherApp/index.html
  JavaScript/weatherApp/script.js
  JavaScript/weatherApp/style.css
Labels: Hacktoberfest

#76 Added todo app
  React/todo-app/.gitignore
  React/todo-app/README.md
  React/todo-app/package-lock.json
  React/todo-app/package.json
  React/todo-app/public/favicon.ico
  React/todo-app/public/index.html
  React/todo-app/public/logo192.png
  React/todo-app/public/logo512.png
  React/todo-app/public/manifest.json
  React/todo-app/public/robots.txt
  React/todo-app/src/App.css
  React/todo-app/src/App.js
  React/todo-app/src/App.test.js
  React/todo-app/src/index.css
  React/todo-app/src/index.js
  React/todo-app/src/logo.svg
  React/todo-app/src/reportWebVitals.js
  React/todo-app/src/setupTests.js
Labels: hacktoberfest-accepted

#77 Add neural-pen-ai-assignment-writer
  Python/AI_Assignment_Writer/.gitignore
  Python/AI_Assignment_Writer/README.md
  Python/AI_Assignment_Writer/llama3.py
  Python/AI_Assignment_Writer/main.py
  Python/AI_Assignment_Writer/requirements.txt
Labels: hacktoberfest-accepted, Hacktoberfest

#78 A simple calculator
  JavaScript/SimpleCalculator/index.html
  JavaScript/SimpleCalculator/script.js
  JavaScript/SimpleCalculator/styles.css
Labels: Hacktoberfest

#82 Create stopwatch.md
  Python/stopwatch/stopwatch.md
Labels: Hacktoberfest

#79 New React Calculator project
  React/calculator/.gitignore
  React/calculator/README.md
  React/calculator/package-lock.json
  React/calculator/package.json
  React/calculator/public/favicon.ico
  React/calculator/public/index.html
  React/calculator/public/logo192.png
  React/calculator/public/logo512.png
  React/calculator/public/manifest.json
  React/calculator/public/robots.txt
  React/calculator/src/App.css
  React/calculator/src/App.js
  React/calculator/src/App.test.js
  React/calculator/src/index.css
  React/calculator/src/index.js
  React/calculator/src/reportWebVitals.js
  React/calculator/src/setupTests.js
Labels: Hacktoberfest

#81 Added simple javascript stopwatch app
  JavaScript/stopwatch/app.js
  JavaScript/stopwatch/index.html
  JavaScript/stopwatch/pause.png
  JavaScript/stopwatch/play.png
  JavaScript/stopwatch/stop.png
  JavaScript/stopwatch/stopwatch.png
  JavaScript/stopwatch/style.css
Labels: Hacktoberfest

#84 added simple interest calculator
  JavaScript/SimpleInterestCalculator/index.html
  JavaScript/SimpleInterestCalculator/index.js
Labels: hacktoberfest-accepted

#92 Added a new React proyect - memory game
  React/memory-game/.gitignore
  React/memory-game/README.md
  React/memory-game/package-lock.json
  React/memory-game/package.json
  React/memory-game/public/favicon.ico
  React/memory-game/public/img/astronaut.png
  React/memory-game/public/img/back.png
  React/memory-game/public/img/moon.png
  React/memory-game/public/img/planet.png
  React/memory-game/public/img/rocket.png
  React/memory-game/public/img/saturn.png
  React/memory-game/public/img/star.png
  React/memory-game/public/index.html
  React/memory-game/public/logo192.png
  React/memory-game/public/logo512.png
  React/memory-game/public/manifest.json
  React/memory-game/public/robots.txt
  React/memory-game/src/App.css
  React/memory-game/src/App.js
  React/memory-game/src/App.test.js
  React/memory-game/src/components/Board.js
  React/memory-game/src/components/Card.js
  React/memory-game/src/index.css
  React/memory-game/src/index.js
  React/memory-game/src/logo.svg
  React/memory-game/src/reportWebVitals.js
  React/memory-game/src/setupTests.js
  React/memory-game/src/styles/App.css
  React/memory-game/src/styles/Board.css
  React/memory-game/src/styles/Card.css
Labels: Hacktoberfest

#93 Add beginner guide for testing Python code with unittest (Fixes #91)
  Python/how_to_test_code.py
Labels: Hacktoberfest

#90 git: add gitignores for the different languages
  Android/Java/.gitignore
  Android/Kotlin/.gitignore
  Android/React Native/.gitignore
  C#/.gitignore
  Cpp/.gitignore
  JavaScript/.gitignore
  Python/.gitignore
  React/.gitignore
Labels: Hacktoberfest

#95 Add unit tests for BankAccount with OOP structure (#94)
  Python/Unit_Test_with_OOPs.py
Labels: Hacktoberfest

#97 Add Audio Adjuster Application (Fixes #96)
  Python/Audio_Adjuster.py
Labels: Hacktoberfest
